
--BRANCH01
--Tao va cap quyen cho BRANCH02
CREATE USER BRANCH01 IDENTIFIED BY BRANCH01;
GRANT CONNECT,DBA TO BRANCH01;

--Tao va cap quyen cho DIRECTOR 
CREATE USER DIRECTOR IDENTIFIED BY DIRECTOR;
GRANT CONNECT TO DIRECTOR;
GRANT SELECT,UPDATE,INSERT,DELETE ON BRANCH01.Warehouse_Imports TO DIRECTOR;
GRANT SELECT,UPDATE,INSERT,DELETE ON BRANCH01.Warehouse_Manages TO DIRECTOR;
GRANT SELECT,UPDATE,INSERT,DELETE ON BRANCH01.Employees TO DIRECTOR;
GRANT SELECT,UPDATE,INSERT,DELETE ON BRANCH01.Payments TO DIRECTOR;
GRANT SELECT,UPDATE,INSERT,DELETE ON BRANCH01.Payment_Details TO DIRECTOR;
GRANT SELECT,UPDATE,INSERT,DELETE ON BRANCH01.Branches TO DIRECTOR;
GRANT SELECT,UPDATE,INSERT,DELETE ON BRANCH01.Customers TO DIRECTOR;
GRANT SELECT,UPDATE,INSERT,DELETE ON BRANCH01.Phones TO DIRECTOR;

--Tao va cap quyen cho MANAGER
CREATE USER "MANAGER" IDENTIFIED BY "MANAGER";
GRANT CONNECT TO "MANAGER";
GRANT SELECT ON BRANCH01.Warehouse_Imports TO "MANAGER";
GRANT SELECT ON BRANCH01.Employees TO "MANAGER";
GRANT SELECT ON BRANCH01.Customers TO "MANAGER";
GRANT SELECT ON BRANCH01.Warehouse_Manages TO "MANAGER";
GRANT SELECT ON BRANCH01.Phones TO "MANAGER";
GRANT SELECT ON BRANCH01.Payments TO "MANAGER";
GRANT SELECT ON BRANCH01.Payment_Details TO "MANAGER";

--Tao va cap quyen cho STAFF
CREATE USER STAFF IDENTIFIED BY STAFF;
GRANT CONNECT TO STAFF;
GRANT SELECT ON BRANCH01.Phones TO STAFF;
GRANT SELECT ON BRANCH01.Warehouse_Manages TO STAFF;
GRANT SELECT ON BRANCH01.Customers TO STAFF;

--Tao Database Link connect voi chi nhanh 2
CREATE PUBLIC DATABASE LINK DBL_M02 CONNECT TO DIRECTOR IDENTIFIED BY DIRECTOR USING 'M02';


--BRANCH02
-- Tao va cap quyen cho BRANCH02
CREATE USER BRANCH02 IDENTIFIED BY BRANCH02;
GRANT CONNECT,DBA TO BRANCH02;

--Tao va cap quyen cho DIRECTOR 
CREATE USER DIRECTOR IDENTIFIED BY DIRECTOR;
GRANT CONNECT TO DIRECTOR;
GRANT SELECT, DELETE, INSERT, UPDATE ON BRANCH02.Warehouse_Imports TO DIRECTOR;
GRANT SELECT, DELETE, INSERT, UPDATE ON BRANCH02.Warehouse_Manages TO DIRECTOR;
GRANT SELECT, DELETE, INSERT, UPDATE ON BRANCH02.Employees TO DIRECTOR;
GRANT SELECT, DELETE, INSERT, UPDATE ON BRANCH02.Payments TO DIRECTOR;
GRANT SELECT, DELETE, INSERT, UPDATE ON BRANCH02.Payment_Details TO DIRECTOR;
GRANT SELECT, DELETE, INSERT, UPDATE ON BRANCH02.Branches TO DIRECTOR;
GRANT SELECT, DELETE, INSERT, UPDATE ON BRANCH02.Customers TO DIRECTOR;
GRANT SELECT, DELETE, INSERT, UPDATE ON BRANCH02.Phones TO DIRECTOR;

--Tao va cap quyen cho MANAGER
CREATE USER MANAGER IDENTIFIED BY "MANAGER";
GRANT CONNECT TO "MANAGER";
GRANT SELECT ON BRANCH02.Warehouse_Imports TO"MANAGER";
GRANT SELECT ON BRANCH02.Employees TO "MANAGER";
GRANT SELECT ON BRANCH02.Customers TO "MANAGER";
GRANT SELECT ON BRANCH02.Warehouse_Manages TO "MANAGER";
GRANT SELECT ON BRANCH02.Phones TO "MANAGER";
GRANT SELECT ON BRANCH02.Payments TO "MANAGER";
GRANT SELECT ON BRANCH02.Payment_Details TO "MANAGER";

--Tao va cap quyen cho STAFF
CREATE USER STAFF IDENTIFIED BY STAFF;
GRANT CONNECT TO STAFF;
GRANT SELECT ON BRANCH02.Phones TO STAFF;
GRANT SELECT ON BRANCH02.Warehouse_Manages TO STAFF;
GRANT SELECT ON BRANCH02.Customers TO STAFF;

--Tao Database Link connect voi chi nhanh 1
CREATE PUBLIC DATABASE LINK DBL_M01 CONNECT TO DIRECTOR IDENTIFIED BY DIRECTOR USING 'M01';
